### ISSUE TITLE
How to build and run HybridDroid ?

### ISSUE THREAD

**Issue by LouisonGitzinger** [SunghoLee/HybriDroid#2]
Hello, I've read your paper about HybriDroid, and I would like to try it. 
How can I build and run the tool ?

**Comment by SunghoLee** [comment]
Thank you for your interest in HybriDroid!

Currently, you can use intelliJ or Eclipse to build and run HybriDroid. Then, you should define some dependencies among WALA and HybriDroid modules. 

We will make a new build script for HybriDroid as soon as possible. Before it, please use an IDE tool. Sorry for the inconvenience.

**Comment by SunghoLee** [comment]
I uploaded an ant build script extracted from intelliJ. Now, you can use the build script :) You should install intelliJ at first, and run the script using ant.

Thank you :)

**Comment by LouisonGitzinger** [comment]
Ok thank you, I will try that !

**Comment by annabeltay** [comment]
Hello, I tried to run the ant build script on intelliJ but I get the following error:
```
taskdef class com.intellij.ant.Javac2 cannot be found
```
Any help on fixing the issue will be greatly appreciated! :)

**Comment by SunghoLee** [comment]
Hi annabeltay.

You should modify your intelliJ and jdk.1.8 paths in the _build.xml_. I updated a new _build.xml_ that has a comment pointing the location that you should modify(from _Modify this: start_ to _Modify this: end_). And I found a missing library, so it was updated. 

Thank you :)

**Comment by annabeltay** [comment]
Hi @SunghoLee Thank you for your reply! I was able to run the build script for Hybridroid after changing the paths like you indicated. However, I was not able to run the `Hybridoid.jar` that was produced from the build script. May I get some help on that matter? Thanks!

**Comment by SunghoLee** [comment]
I'm sorry for missing the main class in `build.xml`. Now, I added the information of the main class `in build.xml`, so you can run HybriDroid in a command line.
The main class of HybriDroid is `kr.ac.kaist.wala.hybridroid.shell.Shell`, and you can construct the call graph of an hybrid app using this command, `java -jar HybriDroid.jar -p wala.properties -t app.apk -cfg. First of all, you should modify some paths in `wala.properties`, so that HybriDroid can find your Java path and Android rt path correctly.

Thank you :)

**Comment by annabeltay** [comment]
@SunghoLee Thank you so much for all your fast replies! I tried to run HybriDroid on `HelloHybrid.apk` with the command like you specified. However, HybriDroid throws an exception before producing the callgraph. The stack trace is as follows:
```
$ java -jar kr.ac.kaist.wala.hybridroid.jar -p /Users/***/HybriDroid/kr.ac.kaist.wala.hybridroid/wala.properties -t HelloHybrid.apk -cfg
#lib: /Users/***/HybriDroid/data/android.jar(true)
I: Using Apktool 2.0.2 on HelloHybrid.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/***/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
===== App Data =====

  version: 2.0.2
  apkFileName: HelloHybrid.apk
  isFrameworkApk: false
  usesFramework:
    ids: -1
  sdkInfo:
    minSdkVersion: '8'
    targetSdkVersion: '21'
  packageInfo:
    forced-package-id: '127'
  versionInfo:
    versionCode: '1'
    versionName: '1.0'
  sharedLibrary: false
  doNotCompress: -resources.arsc
====================
Field Def analysis...
Build Constraint Graph...
Optimize Constraint Graph...
Solving the constraints...
#StringAnalysisEndTime: 20352
===== Not Found Error =====
===========================
Graph Modeling for taint...
Taint analysis...
Exception in thread "main" java.lang.ExceptionInInitializerError
  at kr.ac.kaist.wala.hybridroid.shell.Shell.main(Shell.java:118)
Caused by: java.lang.IllegalArgumentException: null tref
  at com.ibm.wala.types.MethodReference.findOrCreate(MethodReference.java:104)
  at com.ibm.wala.types.MethodReference.findOrCreate(MethodReference.java:127)
  at kr.ac.kaist.wala.hybridroid.test.PrivateLeakageDetector.<clinit>(PrivateLeakageDetector.java:113)
  ... 1 more
```
Do you happen to have an idea of the cause? Thank you once again for taking the time help me on these issues!

**Comment by SunghoLee** [comment]
The error occured in `PrivateLeakageDetector`, so building a call graph is finished. `PrivateLeakageDetector` is used to track data flows from sources to sinks. It is not necessary to build the call graph of an app. I will check the exception in several days. 

However, you can build a call graph for hybrid apps regardless of the exception. I commented out unimportant lines for building a call graph, and checked that the call graph is constructed correctly about `HelloHybrid.apk`.

Please check this revision, try to run it, and let me know your result. 
Thank you!

**Comment by tiandiyixian** [comment]
I  encountered the same problem.When  I use the command java -jar kr.ac.kaist.wala.hybridroid.jar -p wala.properties -t ***.apk -cfg,actually，when  I  used  the taint analysis  with  any  apk,the  same    error   report is   as  flollow:
Caused by: java.lang.IllegalArgumentException: null tref
  at com.ibm.wala.types.MethodReference.findOrCreate(MethodReference.java:104)
  at com.ibm.wala.types.MethodReference.findOrCreate(MethodReference.java:127)
  at kr.ac.kaist.wala.hybridroid.test.PrivateLeakageDetector.<clinit>(PrivateLeakageDetector.java:113)
I  cannot find  the  reason,Maybe  TypeReference.find(JavaScriptTypes.jsLoader, "Lpreamble.js/XMLHttpRequest/xhr_send")   should be  TypeReference.findOrCreate(JavaScriptTypes.jsLoader, "Lpreamble.js/XMLHttpRequest/xhr_send")?
I am very confused

**Comment by arvind4141** [comment]
Hello there! I've recently built this project successfully too, but I'm getting the same taint analysis error as above as well. I would like to know is there any solution to this? Thank you!

**Comment by SunghoLee** [comment]
Hello, sorry for late response.
I fixed the taint analysis bug and the structure of the module is slightly changed. The current module requires registering sources and sinks using `addSource` / `addSink` methods, while previous version did it using static fields in the module.
Please try it, and let me know remaining issues.
Thank you!

**Comment by arvind4141** [comment]
Thank you so much for your response. It works great now! No errors at all, I'm still trying to understand how to get the taint paths to print out. Because even with my hybrid APK that has leaked tainted information, HybriDroid is not detecting it. 
I presume it has to do with me setting the source and sink methods.
By any chance, do you have an example APK along with an example source and sink method that would work out and print taint paths from that APK? 
Once again, thank you so much for your help so far. I really appreciate it!

**Comment by SunghoLee** [comment]
Sorry for late response. I make HybriDroid to being built by Gradle build system, so now you can build it in the fast and easy way as well as libraries are automatically downloaded.

And, HybriDroid may miss taint flows because Android apps have many implicit flows, even though  I cannot confirm the reason because I don't know the taint paths in your app.
You can check how the taint analyzer works using this APK file(https://drive.google.com/file/d/1POBQxM8ojbEKsHjvqmmZa_0yys2d9643/view?usp=sharing) and below a source and a sink.
source:
`MethodReference.findOrCreate(TypeReference.find(ClassLoaderReference.Application, "Landroid/telephony/TelephonyManager"), Selector.make("getLine1Number()Ljava/lang/String;"))
`
sink:
`MethodReference.findOrCreate(TypeReference.find(JavaScriptTypes.jsLoader, "Lpreamble.js/XMLHttpRequest/xhr_send"), Selector.make("do()LRoot"))`
When you get the result, please let me know about that.
Thank you!
